# Azure Container Apps configuration for Laravel Docker application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel-app
        image: ${CONTAINER_REGISTRY}/laravel-docker-app:${BUILD_ID}
        ports:
        - containerPort: 9000
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: app-key
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: redis-password
        - name: CACHE_DRIVER
          value: "redis"
        - name: SESSION_DRIVER
          value: "redis"
        - name: QUEUE_CONNECTION
          value: "redis"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
      - name: nginx
        image: ${CONTAINER_REGISTRY}/laravel-docker-app-nginx:${BUILD_ID}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
          readOnly: true
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: laravel-storage-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  labels:
    app: laravel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: laravel

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  db-host: "laravel-mysql.mysql.database.azure.com"
  db-database: "laravel"
  redis-host: "laravel-redis.redis.cache.windows.net"
  app-url: "https://laravel-app.azurecontainerapps.io"

---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
data:
  app-key: # Base64 encoded APP_KEY
  db-username: # Base64 encoded database username
  db-password: # Base64 encoded database password
  redis-password: # Base64 encoded Redis password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile

---
# Queue worker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-queue
  labels:
    app: laravel-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-queue
  template:
    metadata:
      labels:
        app: laravel-queue
    spec:
      containers:
      - name: queue-worker
        image: ${CONTAINER_REGISTRY}/laravel-docker-app:${BUILD_ID}
        command: ["php", "artisan", "queue:work"]
        args: ["--sleep=3", "--tries=3", "--max-time=3600", "--daemon"]
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: app-key
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: redis-password
        - name: QUEUE_CONNECTION
          value: "redis"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: laravel-storage-pvc

---
# Scheduler deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-scheduler
  labels:
    app: laravel-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-scheduler
  template:
    metadata:
      labels:
        app: laravel-scheduler
    spec:
      containers:
      - name: scheduler
        image: ${CONTAINER_REGISTRY}/laravel-docker-app:${BUILD_ID}
        command: ["/bin/sh"]
        args: ["-c", "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"]
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: app-key
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: db-database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: db-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-config
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: redis-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: laravel-storage-pvc
